### ISSUE TITLE
Prepare for Dataverse v4.0 compatibility

### ISSUE THREAD

**Issue by leeper** [ropensci/dvn#23]
[Compatibility guide](https://docs.google.com/document/d/11DpdKyp1tagmaJAAzRqQBEZEZ69WOOOYsoqhz8UsfNM/edit) (archived)

[Harvard Demo server running v4.0](https://dataverse-demo.iq.harvard.edu/)

[API Guide](http://guides.dataverse.org/en/latest/api/index.html)

**Comment by pdurbin** [comment]
Thanks for creating this ticket @leeper ! A few things...

Per http://guides.dataverse.org/en/latest/api there is an additional server I've set up specifically for API testing at https://apitest.dataverse.org where I [deploy the latest code](https://build.hmdc.harvard.edu:8443/job/apitest.dataverse.org-deploy/) (more often than on the "demo" server), run some [post-deployment tests](https://github.com/IQSS/dataverse-apitester), and [share the results](https://build.hmdc.harvard.edu:8443/job/apitest.dataverse.org-apitester/). It might be a better place for testing.

I also wanted to point out that a new Dataverse API Community Group is forming at http://community.dataverse.org/community-groups/api.html and everyone is welcome to join!

For my own reference, I'll include a link to an [internal ticket](https://help.hmdc.harvard.edu/Ticket/Display.html?id=178922) where we've had a bit of discussion about backwards compatibility of APIs.

Finally, I sort of consider "DVN" to be a deprecated term. It stood for "Dataverse Network" and referred to software such as DVN 3.6. We're now dropping "Network" and calling the software "Dataverse 4.0". I'd be curious to hear your thoughts on the possibility of changing the name of the R package. I'm not trying to complicate things for you and of course it's fine to continue calling it "dvn", but I just wanted to put a bug in your ear about this! :)

Thanks so much for all of your hard work creating and supporting this package! We really appreciate it!

**Comment by leeper** [comment]
@pdurbin Thanks for the updated info. This has been on my backburner for a while, so it's helpful to get a status update. My current thinking is to launch a new package, so "dvn" will remain the package for using Dataverse < 4.0 (for backwards compatibility) and a new package with a new name (maybe just "dataverse"?) will be tailored around Dataverse >= 4.0.

I'm also thinking about writing a separate SWORD package (as we talked about a long time ago), so the new "dataverse" package will simply import that generic functionality.

Let me know how that all sounds to you.

**Comment by pdurbin** [comment]
@leeper if you start a new R package called "dataverse" please let me know! @cchoirat has been asking me about an R package that's focused on Dataverse 4.0 and higher. (Separately, I've been chatting with @rliebz and @raprasad about the possibility of a Python version.) If it's not too much work for you to maintain both packages, I think it's a great idea. Also, if you think it might make more sense to put the new "dataverse" package under the @IQSS GitHub organization, please just say the word.

SWORD spec lead @richard-jones seemed very enthusiastic about a separate SWORD package for R and [back in late 2013](https://www.mail-archive.com/sword-app-tech@lists.sourceforge.net/msg00363.html) he and I were hoping that someone could build off your work. If you're now saying that you might be able to do this work yourself, so much the better!

**Comment by leeper** [comment]
@pdurbin Okay, let me put some thought on this and I'll get back to you.

**Comment by pdurbin** [comment]
Heads up about https://github.com/IQSS/dataverse/commit/3b57027 and http://datascience.iq.harvard.edu/blog/dataverse-40-next-week ! :)

Sounds like you're making [good progress](https://twitter.com/thosjleeper/status/586812290411995136)! If there's anything you need, just let us know!

I recently started putting API-related integration tests right in our main repo: https://github.com/IQSS/dataverse/blob/8496b4235bedd83aa1014bc9731b324f71478072/src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java

Finally, @rliebz has been working away in this branch in Python if it's of interest: https://github.com/rliebz/dataverse-client-python/tree/4.0

**Comment by pdurbin** [comment]
The news on this end:

- new page on client libraries (including this one!): http://guides.dataverse.org/en/latest/api/client-libraries.html
- https://github.com/IQSS/dataverse-client-python how has Travis CI tests: https://travis-ci.org/IQSS/dataverse-client-python (passing even) :)
- we tagged Dataverse 4.0: https://github.com/IQSS/dataverse/releases/tag/4.0
- I recently posted this: [[sword-app-tech] Should we extend the Repository API beyond SWORD?](http://www.mail-archive.com/sword-app-tech@lists.sourceforge.net/msg00431.html)
- I mentioned this very issue #23 today: https://groups.google.com/forum/#!topic/dataverse-community/fFrJi7NnBus :)

If there's anything you need from me, please let me know! As always, thanks for all you do for Dataverse! :)

**Comment by leeper** [comment]
Thanks for the updates! This is coming along, but I think what my current release plans are as follows:

 1. [ ] Release new R client here: https://github.com/leeper/dataverse with minimum support for the search API, the data access API, and (hopefully) the native API. This will import [the UNF package](http://cran.r-project.org/web/packages/UNF/index.html) so that users can verify datasets locally against the metadata provided by the Dataverse.
 2. [ ] Release a generic SWORD client here: https://github.com/leeper/SWORD. This will aim to work for Dataverse, [Archivematica](https://www.archivematica.org/wiki/Sword_API), and [arXiv](http://arxiv.org/help/submit_sword).
 3. [ ] Import the SWORD client into the **dataverse** package and write some custom wrappers (essentially rebuilding the entire deposit workflow from **dvn**). (Programming style note: I think it will use reference class semantics from [R6](http://cran.r-project.org/web/packages/R6/index.html) rather than the function approach I used in **dvn**.)
 4. [ ] Deprecate **dvn** and point new users to **dataverse**.

**Comment by pdurbin** [comment]
> Release new R client here: https://github.com/leeper/dataverse

@leeper how do you feel about https://github.com/IQSS/dataverse-client-r as a URL? This would mirror https://github.com/IQSS/dataverse-client-python and I would be happy to create that repo and give you push access like I did for @rliebz for the Python equivalent! I can also enable Travis for you. Whatever you want. :) There are developers at @IQSS such as @cchoirat who have been hoping to see an official R package for Dataverse under the @IQSS GitHub organization. And maybe she'll be able to help out. ;)

No matter what the final URL is, I'm quite happy to update http://guides.dataverse.org/en/latest/api/client-libraries.html when the Dataverse 4.0-compatible version is available! As you mentioned, a pointing users from the old "dvn" package to the new "dataverse" package will be quite helpful!

**Comment by leeper** [comment]
[This](https://github.com/IQSS/dataverse/issues/2407) sounds like a plan. It's on my agenda for August (I'm moving on the 12th and will try to put it all together the week after that).

**Comment by pdurbin** [comment]
@leeper great! Sorry, when you mentioned https://github.com/IQSS/dataverse/pull/2407#issuecomment-126735269 did you mean that you'd like me to create a repo under @IQSS for you? I'm happy to do so! Just say the word! To match https://github.com/IQSS/dataverse-client-python I might call it dataverse-client-r unless you have a name you prefer.

**Comment by leeper** [comment]
@pdurbin Yup, let's do that! `dataverse-client-r` sounds great.

**Comment by pdurbin** [comment]
Ok! I created https://github.com/IQSS/dataverse-client-r and gave you push access.

```sh
git remote add origin git@github.com:IQSS/dataverse-client-r.git
git push -u origin master
```

**Comment by leeper** [comment]
@pdurbin Thanks!

**Comment by leeper** [comment]
@pdurbin I don't think I have write access to https://github.com/IQSS/dataverse-client-r. I tried to push but got a failure message. Can you take a look and make sure permissions are configured for me?

**Comment by pdurbin** [comment]
@leeper sorry! I had created https://github.com/orgs/IQSS/teams/dataverse-client-r but apparently not added that team to the repo. Can you please try again?

**Comment by pdurbin** [comment]
@leeper have you had a chance to re-try pushing to https://github.com/IQSS/dataverse-client-r ? I think the permissions are set up correctly now.

I'm asking because someone just asked on the Dataverse mailing list was just trying to use the old "dvn" package with a Dataverse 4 installation (which won't work, of course): https://groups.google.com/forum/#!topic/dataverse-community/0RmQ7ovfhDs

Thanks again for all the work you've done for Dataverse!

**Comment by leeper** [comment]
@pdurbin Yes! Just pushed an initial draft successfully. There's no documentation yet and it's untested, but it theoretically works. Will make an effort to document and add tests as soon as I can.

**Comment by leeper** [comment]
Closing this, as development for Dataverse >= v4.0 is now here: https://github.com/IQSS/dataverse-client-r
