### ISSUE TITLE
Travis builds?

### ISSUE THREAD

**Issue by sckott** [ropensci/dvn#24]
hi @leeper - I can't get travis builds to start on this repo. Any ideas? Something in the travis file preventing builds from happening?

**Comment by leeper** [comment]
Looks like travis isn't setup (the toggle isn't flipped to initiative builds) and I appear to not have rights to allow builds.

**Comment by sckott** [comment]
blarg, sorry about this. Seemed like builds were broken before I messed with anything. i tried to fix by removing the hook based on your account, but now I can't get any hook to work 

any thoughts @ropensci/owners
